// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_-LFu9cv0XSgmkZgYB6epBusQd_aUUa0',
    appId: '1:190579075787:web:7f6f06d7bf0fb62e81894e',
    messagingSenderId: '190579075787',
    projectId: 'tubes-35d7e',
    authDomain: 'tubes-35d7e.firebaseapp.com',
    storageBucket: 'tubes-35d7e.appspot.com',
    measurementId: 'G-CB014ZREVR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBgYqgXJs4FuR0uzKOZ4cdZQDrUABnMp8',
    appId: '1:190579075787:android:3f1a1aa2a89e478e81894e',
    messagingSenderId: '190579075787',
    projectId: 'tubes-35d7e',
    storageBucket: 'tubes-35d7e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFywIeLf8qcCL0LxvoyAAY9zZgHgg0nXU',
    appId: '1:190579075787:ios:dea1d5e4f2eb039e81894e',
    messagingSenderId: '190579075787',
    projectId: 'tubes-35d7e',
    storageBucket: 'tubes-35d7e.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFywIeLf8qcCL0LxvoyAAY9zZgHgg0nXU',
    appId: '1:190579075787:ios:dea1d5e4f2eb039e81894e',
    messagingSenderId: '190579075787',
    projectId: 'tubes-35d7e',
    storageBucket: 'tubes-35d7e.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_-LFu9cv0XSgmkZgYB6epBusQd_aUUa0',
    appId: '1:190579075787:web:6664a7d026cc029681894e',
    messagingSenderId: '190579075787',
    projectId: 'tubes-35d7e',
    authDomain: 'tubes-35d7e.firebaseapp.com',
    storageBucket: 'tubes-35d7e.appspot.com',
    measurementId: 'G-BTERL97ML0',
  );
}
